ProyectoDental2.0-main-main/citas/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [ 
    path('crear-citas/', views.crearcitas, name="crearcitas"),
    path('editar-citas/<int:cita_id>', views.editarcitas, name="editarcitas"),
    path('list-citas/', views.listcitas, name="listcitas"),
    path('cancelar-cita/<int:cita_id>/', views.cancelar_cita, name='cancelar_cita'),
    path('confirmar-actualizacion/<int:cita_id>/', views.confirmar_actualizacion_cita, name='confirmar_actualizacion_cita'),
    path('get-horas-disponibles/', views.get_horas_disponibles, name='get_horas_disponibles'),
    path('oauth2callback/', views.oauth2callback, name='oauth2callback'),
    path('initiate_oauth/', views.initiate_oauth, name='initiate_oauth'),
]

ProyectoDental2.0-main-main/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from inicio import views
from django.urls import path
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('citas.urls')),
    path('', include('cuentas.urls')),
    path('', include('dashboard.urls')),
    path('', include('fechas.urls')),
    path('', include('historiaclinica.urls')),
    path('', include('inicio.urls')),
    path('', include('inventario.urls')),
    path('gmail/', include('gmail_integration.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoDental2.0-main-main/citas/models.py
from django.db import models

# Create your models here.

ProyectoDental2.0-main-main/inicio/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils import timezone

class UserProfileManager(BaseUserManager):
    def create_user(self, numero, username, email, password=None, tipo=2):
        if not numero:
            raise ValueError('Users must have a document number')
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            numero=numero,
            username=username,
            email=self.normalize_email(email),
            tipo=tipo
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, numero, username, email, password=None, tipo=2):
        user = self.create_user(
            numero=numero,
            username=username,
            email=email,
            password=password,
            tipo=tipo,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class UserProfile(AbstractBaseUser, PermissionsMixin):
    TIPO_CHOICES = (
        (1, 'T.I'),
        (2, 'C.C'),
        (3, 'C.E'),
        (4, 'C.I'),
    )
    
    tipo = models.PositiveSmallIntegerField(choices=TIPO_CHOICES, default=2)
    numero = models.BigIntegerField(unique=True)
    username = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to='imagenes/', blank=True, null=True)
    direccion = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    ocupacion = models.CharField(max_length=50, null=True, blank=True)
    celular = models.CharField(max_length=15, null=True, blank=True)  # Changed to CharField
    acudiente = models.CharField(max_length=50, null=True, blank=True)  # Changed default to blank=True
    edad = models.PositiveSmallIntegerField(null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    is_staff = models.BooleanField(default=False, null=True, blank=True)
    is_admin = models.BooleanField(default=False, null=True, blank=True)
    is_superuser = models.BooleanField(default=False, null=True, blank=True)

    objects = UserProfileManager()

    USERNAME_FIELD = 'numero'
    REQUIRED_FIELDS = ['username', 'email']

    def __str__(self):
        return str(self.numero)

class Valoracion(models.Model):  # Changed to PascalCase
    OPCIONES_SI_NO_NO_SABE = (
        (1, 'Si'),
        (2, 'No'),
        (3, 'Desinformado'),
    )
    OPCIONES_SI_NO = (
        (1, 'Si'),
        (2, 'No'),
    )

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    username = models.CharField(max_length=150, blank=True) 
    numero = models.CharField(max_length=50, blank=True) 
    fecha_historia = models.DateField(null=True, blank=True) 
    tratamiento_medicacion = models.PositiveSmallIntegerField(choices=OPCIONES_SI_NO_NO_SABE, default=3)
    reacciones_alergicas = models.PositiveSmallIntegerField(choices=OPCIONES_SI_NO_NO_SABE, default=3)
    transtorno_tension_arterial = models.PositiveSmallIntegerField(choices=OPCIONES_SI_NO_NO_SABE, default=3)
    diabetes = models.PositiveSmallIntegerField(choices=OPCIONES_SI_NO_NO_SABE, default=3)
    transtornos_emocionales = models.PositiveSmallIntegerField(choices=OPCIONES_SI_NO_NO_SABE, default=3)
    enfermedad_respiratoria = models.PositiveSmallIntegerField(choices=OPCIONES_SI_NO_NO_SABE, default=3)
    otros = models.CharField(max_length=100, blank=True)

    protesis_dental = models.CharField(max_length=100, blank=True)
    total = models.CharField(max_length=100, blank=True)
    acrilico = models.CharField(max_length=100, blank=True)
    flexible = models.CharField(max_length=100, blank=True)
    parcial = models.CharField(max_length=100, blank=True)
    retenedores = models.CharField(max_length=100, blank=True)

    panoramica = models.CharField(max_length=100, blank=True)
    periapical = models.CharField(max_length=100, blank=True)

    cepillado_dental = models.PositiveSmallIntegerField(choices=OPCIONES_SI_NO)
    seda_dental = models.PositiveSmallIntegerField(choices=OPCIONES_SI_NO)
    enjuague_bucal = models.PositiveSmallIntegerField(choices=OPCIONES_SI_NO)

    def save(self, *args, **kwargs):
        if self.user:
            self.username = self.user.username
            self.numero = self.user.numero
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Valoración de {self.username} (Número: {self.numero})"
    

class Inventario(models.Model):
    ESTADO = (
        (1, 'Disponible'),
        (2, 'Agotado'),
        (3, 'Por Recibir'),
    )
    producto = models.CharField(max_length=150, blank=True) 
    cantidad = models.FloatField(blank=True) 
    estado = models.PositiveSmallIntegerField(choices=ESTADO, default=1)

    def save(self, *args, **kwargs):
        if self.cantidad <= 0:
            self.estado = 2
        elif self.estado == 2:
            self.cantidad = 0 
        super().save(*args, **kwargs)

    def __str__(self):
        return self.producto
    

class Fecha(models.Model):
    fecha = models.DateField()
    hora = models.TimeField()
    disponible = models.BooleanField(default=True)

    class Meta:
        unique_together = ('fecha', 'hora')

    def __str__(self):
        return f"{self.fecha} {self.hora}"

    def save(self, *args, **kwargs):
        print(f"Guardando Fecha {self}. Disponible antes de guardar: {self.disponible}")
        super().save(*args, **kwargs)
        print(f"Fecha guardada. Disponible después de guardar: {self.disponible}")


class Cita(models.Model):
    ESTADO_CHOICES = (
        ('programada', 'Programada'),
        ('asistida', 'Asistida'),
        ('cancelada', 'Cancelada'),
        ('inasistida', 'No Asistió'),
    )

    MOTIVO_CHOICES = (
        ('protesis', 'Protesis'),
        ('ortodoncia', 'Ortodoncia'),
    )

    paciente = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    fecha_hora = models.ForeignKey(Fecha, on_delete=models.CASCADE, related_name='citas')
    motivo = models.CharField(max_length=20, choices=MOTIVO_CHOICES, default='protesis')
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='programada')
    asistio = models.BooleanField(default=False)
    google_event_id = models.CharField(max_length=255, blank=True, null=True)  # Campo nuevo

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        self.actualizar_disponibilidad(is_new)
        self.actualizar_estado_por_fecha()


    def actualizar_estado_por_fecha(self):
        if self.fecha_hora.fecha < timezone.now().date() and self.estado == 'programada':
            self.estado = 'inasistida'
            self.save()

    def actualizar_disponibilidad(self, is_new):
        print(f"Actualizando disponibilidad para fecha_hora: {self.fecha_hora}")
        if is_new or self.estado == 'programada':
            self.fecha_hora.disponible = False
        elif self.estado == 'cancelada':
            citas_activas = Cita.objects.filter(
                fecha_hora=self.fecha_hora, 
                estado__in=['programada', 'completada']
            ).exclude(pk=self.pk).exists()
            if not citas_activas:
                self.fecha_hora.disponible = True
        
        print(f"Guardando fecha_hora con disponibilidad: {self.fecha_hora.disponible}")
        self.fecha_hora.save()

    def cancelar_cita(self):
        if self.estado == 'programada':
            self.estado = 'cancelada'
            self.save()
            print(f"Cita cancelada. Nueva disponibilidad de fecha_hora: {self.fecha_hora.disponible}")
            return True
        return False

    def confirmar_actualizacion(self):
        if self.estado == 'programada':
            self.estado = 'completada'
            self.asistio = True
            self.save()
            return True
        return False

    def __str__(self):
        return f"Cita de {self.paciente} el {self.fecha_hora}"

ProyectoDental2.0-main-main/citas/templates/crearcitas.html
{% extends 'index.html' %}

{% load static %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}?v1.2">
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Crear Cita</h4>
        {% include 'formscitas.html' %}
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/citas.js' %}?v2.5"></script> 
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock %}

ProyectoDental2.0-main-main/citas/templates/editarcitas.html
{% extends 'index.html' %}

{% load static %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}?v1.2">
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Editar Cita</h4>
        {% include 'formscitas.html' %}
        
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/citas.js' %}?v2.5"></script> 
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock %}

ProyectoDental2.0-main-main/citas/templates/email_recordatorio.html
<!DOCTYPE html>
<html>
<head>
    <title>Recordatorio: Creación de Cita</title>
</head>
<body>
    <p>Hola {{ cita.paciente.get_full_name }},</p>

    <p>Te informamos que se ha creado una nueva cita para ti:</p>
    <ul>
        <li>Fecha: {{ cita.fecha }}</li>
        <li>Hora: {{ cita.hora }}</li>
        <li>Motivo: {{ cita.get_motivo_display }}</li>
        <!-- Puedes agregar más detalles de la cita según tu modelo -->
    </ul>

    <p>Por favor, contáctanos si necesitas hacer algún ajuste a esta cita.</p>

    <p>Saludos,<br>El equipo de citas</p>
</body>
</html>

ProyectoDental2.0-main-main/citas/templates/formscitas.html
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}?v1.2">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock %}

{% block content %}
<form method="POST" id="citaForm">
  {% csrf_token %}

  <div class="mb-3">
    <label for="fecha" class="form-label">Fecha: </label>
    <input type="text" class="form-control" id="fecha" name="fecha" required>
  </div>

  <div class="mb-3">
    <label class="form-label">Hora: </label>
    <div id="hora" class="form-check">
      <!-- Las opciones se llenarán con JavaScript -->
    </div>
  </div>

  <div class="mb-3">
    <label for="motivo" class="form-label">Motivo: </label>
    <select class="form-select" name="motivo" id="motivo" required>
      {% for value, display_name in form.fields.motivo.choices %}
      <option value="{{ value }}">{{ display_name }}</option>
      {% endfor %}
    </select>

    {% if is_superuser %}
    <div class="mb-3">
      <label for="paciente" class="form-label">Seleccionar Paciente: </label>
      <select class="form-select" name="paciente" id="paciente" required>
        {% for value, display_username in form.fields.paciente.choices %}
        <option value="{{ value }}">{{ display_username }}</option>
        {% endfor %}
      </select>
    </div>
    {% else %}
    <input type="hidden" name="paciente" value="{{ cita.paciente.id }}">
    <p>{{ cita.paciente.get_username }}</p>
    {% endif %}

  </div>
  <button type="submit" class="btn btn-success">Guardar</button>
  <a class="btn btn-warning" href="{% url 'listcitas' %}" role="button">Volver</a>
</form>
{% endblock %}

{% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="{% static 'js/citas.js' %}"></script>
<script>
  flatpickr("#fecha", {
    enableTime: false, // No es necesario si solo se necesita fecha
    dateFormat: "Y-m-d", // Formato de fecha a enviar al servidor
    locale: "es", // Configura el idioma
  });
</script>
{% endblock %}

ProyectoDental2.0-main-main/citas/templates/listcitas.html
{% extends 'index.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/elementos.css' %}?v1.2">
{% endblock %}

{% block titulo %}
Citas Agendadas
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header d-flex justify-content-between">
        <a class="btn btn-primary btn-custom" href="{% url 'dashboard' %}" role="button">
            <i class="fas fa-arrow-left text-white"></i> Volver
        </a>
        <a class="btn btn-success btn-custom" href="{% url 'crearcitas' %}" role="button">
            <i class="fas fa-plus text-white"></i> Agendar Nueva Cita
        </a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-primary">
                <thead>
                    <tr>
                        <th scope="col">Paciente</th>
                        <th scope="col">Nombres</th>
                        <th scope="col">Fecha</th>
                        <th scope="col">Hora</th>
                        <th scope="col">Motivo</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Reagendar</th>
                        <th scope="col">Cancelar</th>
                        {% if user.is_superuser %}
                        <th scope="col">Actualizar</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for cita in citas %}
                    <tr>
                        <td>{{ cita.paciente }}</td>
                        <td>{{ cita.paciente.username }}</td>
                        <td>{{ cita.fecha_hora.fecha|date:"d-m-Y" }}</td>
                        <td>{{ cita.fecha_hora.hora|time:"H:i" }}</td>
                        <td>{{ cita.get_motivo_display }}</td>
                        <td>{{ cita.get_estado_display }}</td>
                        <td>
                            <a {% if cita.estado == 'programada' %}href="{% url 'editarcitas' cita.id %}" class="btn btn-warning"{% else %}class="btn btn-secondary disabled"{% endif %}>Reagendar Cita</a>
                        </td>
                        <td>
                            <button {% if cita.estado == 'programada' %}class="btn btn-danger cancelar-cita-btn"{% else %}class="btn btn-secondary disabled"{% endif %} data-cita-id="{{ cita.id }}">Cancelar
                                Cita</button>
                        </td>
                        <td>
                            {% if user.is_superuser %}
                            <button {% if cita.estado == 'programada' %}class="btn btn-info confirmar-actualizacion-btn"{% else %}class="btn btn-secondary disabled"{% endif %} data-cita-id="{{ cita.id }}">Actualizar Asistencia</button>
                            {% endif %}
                        </td>
                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

{% block extra_js %}
<script src="{% static 'js/citas.js' %}?v2.8"></script>
{% endblock %}